"""ClawBox 墨水屏 21 种语言文案。渲染与测宽逻辑见 screen_pages.py。

与前端 i18n.config.ts 的 21 种语言对齐 (pt-BR 由 pt 承担)。ar/fa 为从右到左
书写的 RTL 语言, 由 screen_pages 联动 screen_text 的 direction=rtl 渲染。
"""

# 各页面文案按语言分组。英文遵循"先放得下、再达意"原则,
# 全部控制在 146px 渲染宽度内 (152px 屏 - 左右边距)
STRINGS = {
    "zh-CN": {
        "help_buttons": "按键",
        "help_k1": "扫码访问",
        "help_k2": "聊天渠道",
        "help_k3": "WiFi 状态",
        "help_k4_short": "短按=重启",
        "help_k4_long": "长按=关机",
        "help_hint": "长按 K1 查看本说明",
        "lan_qr": "扫码进入网页",
        "waiting_title": "等待服务启动",
        "waiting_line2": "网页端生成后",
        "waiting_line3": "自动刷新显示",
        "qr_expired_title": "二维码已过期",
        "qr_expired_line2": "如尚未连接成功",
        "qr_expired_line3": "请重新获取",
        "wifi_status": "WiFi 状态",
        "hotspot": "热点模式",
        "waiting_phone": "等待手机连接",
        "connected": "已连接",
        "unknown": "状态未知",
        "check_network": "检查网络...",
        "please_wait": "请稍候",
        "disconnecting": "正在断开 WiFi...",
        "restart_hotspot": "设备将重启热点",
        "boot_subtitle": "AI 网关设备",
        "booting": "正在启动...",
        "error_title": "出错啦",
    },
    "zh-TW": {
        "help_buttons": "按鍵",
        "help_k1": "掃碼訪問",
        "help_k2": "聊天渠道",
        "help_k3": "WiFi 狀態",
        "help_k4_short": "短按=重啟",
        "help_k4_long": "長按=關機",
        "help_hint": "長按 K1 查看說明",
        "lan_qr": "掃碼進入網頁",
        "waiting_title": "等待服務啟動",
        "waiting_line2": "網頁端生成後",
        "waiting_line3": "自動刷新顯示",
        "qr_expired_title": "二維碼已過期",
        "qr_expired_line2": "如尚未連接成功",
        "qr_expired_line3": "請重新獲取",
        "wifi_status": "WiFi 狀態",
        "hotspot": "熱點模式",
        "waiting_phone": "等待手機連接",
        "connected": "已連接",
        "unknown": "狀態未知",
        "check_network": "檢查網路...",
        "please_wait": "請稍候",
        "disconnecting": "正在斷開 WiFi...",
        "restart_hotspot": "裝置將重啟熱點",
        "boot_subtitle": "AI 閘道裝置",
        "booting": "正在啟動...",
        "error_title": "發生錯誤",
    },
    "en": {
        "help_buttons": "Buttons",
        "help_k1": "Scan QR",
        "help_k2": "Chats",
        "help_k3": "WiFi",
        # 英文 K4 用竖排括号布局(见 render_help_page): 两行均为"动作+结果"紧凑文案,
        # 152px 屏放不下带 "=" 的长写法 (Tap=Reboot / Hold=Power off)
        "help_k4_short": "Tap  Reboot",
        "help_k4_long": "Hold  Power",
        "help_hint": "Hold K1 for help",
        "lan_qr": "Scan to open",
        "waiting_title": "Waiting...",
        "waiting_line2": "Generate on web",
        "waiting_line3": "Auto refresh",
        "qr_expired_title": "QR expired",
        "qr_expired_line2": "Not paired yet",
        "qr_expired_line3": "Get a new one",
        "wifi_status": "WiFi Status",
        "hotspot": "Hotspot",
        "waiting_phone": "Waiting for phone",
        "connected": "Connected",
        "unknown": "Unknown",
        "check_network": "Check network...",
        "please_wait": "Please wait",
        "disconnecting": "Disconnecting WiFi...",
        "restart_hotspot": "Hotspot will restart",
        "boot_subtitle": "AI Gateway",
        "booting": "Starting...",
        "error_title": "Error",
    },
    "ja": {
        "help_buttons": "ボタン",
        "help_k1": "スキャン",
        "help_k2": "チャット",
        "help_k3": "WiFi",
        "help_k4_short": "短押=再起動",
        "help_k4_long": "長押=電源切",
        "help_hint": "K1 長押でヘルプ",
        "lan_qr": "スキャンで開く",
        "waiting_title": "待機中...",
        "waiting_line2": "ウェブで生成後",
        "waiting_line3": "自動更新",
        "qr_expired_title": "QR 有効期限切れ",
        "qr_expired_line2": "未接続の場合",
        "qr_expired_line3": "再取得して下さい",
        "wifi_status": "WiFi 状態",
        "hotspot": "ホットスポット",
        "waiting_phone": "スマホ接続待ち",
        "connected": "接続済み",
        "unknown": "不明",
        "check_network": "ネット確認...",
        "please_wait": "少々お待ち下さい",
        "disconnecting": "WiFi 切断中...",
        "restart_hotspot": "ホットスポット再起動",
        "boot_subtitle": "AI ゲートウェイ",
        "booting": "起動中...",
        "error_title": "エラー",
    },
    "ko": {
        "help_buttons": "버튼",
        "help_k1": "스캔 접속",
        "help_k2": "채팅",
        "help_k3": "WiFi",
        "help_k4_short": "짧게=재시작",
        "help_k4_long": "길게=전원끔",
        "help_hint": "K1 길게=도움말",
        "lan_qr": "스캔하여 열기",
        "waiting_title": "서비스 대기",
        "waiting_line2": "웹에서 생성 후",
        "waiting_line3": "자동 갱신",
        "qr_expired_title": "QR 만료됨",
        "qr_expired_line2": "아직 연결 안됨",
        "qr_expired_line3": "다시 받으세요",
        "wifi_status": "WiFi 상태",
        "hotspot": "핫스팟",
        "waiting_phone": "휴대폰 대기",
        "connected": "연결됨",
        "unknown": "알 수 없음",
        "check_network": "네트워크 확인...",
        "please_wait": "잠시만요",
        "disconnecting": "WiFi 해제 중...",
        "restart_hotspot": "핫스팟 재시작",
        "boot_subtitle": "AI 게이트웨이",
        "booting": "시작 중...",
        "error_title": "오류",
    },
    "es": {
        "help_buttons": "Botones",
        "help_k1": "Escanear QR",
        "help_k2": "Chats",
        "help_k3": "WiFi",
        "help_k4_short": "Tocar=Reiniciar",
        "help_k4_long": "Mantener=Apagar",
        "help_hint": "Mantener K1=ayuda",
        "lan_qr": "Escanear QR",
        "waiting_title": "Esperando...",
        "waiting_line2": "Generar en web",
        "waiting_line3": "Auto actualiza",
        "qr_expired_title": "QR caducado",
        "qr_expired_line2": "Si no conectado",
        "qr_expired_line3": "Obtener uno nuevo",
        "wifi_status": "Estado WiFi",
        "hotspot": "Punto acceso",
        "waiting_phone": "Esperando teléfono",
        "connected": "Conectado",
        "unknown": "Desconocido",
        "check_network": "Revisar red...",
        "please_wait": "Espere por favor",
        "disconnecting": "Desconectando WiFi...",
        "restart_hotspot": "Reiniciar hotspot",
        "boot_subtitle": "Puerta AI",
        "booting": "Iniciando...",
        "error_title": "Error",
    },
    "de": {
        "help_buttons": "Tasten",
        "help_k1": "QR scannen",
        "help_k2": "Chats",
        "help_k3": "WiFi",
        "help_k4_short": "Tippen=Neustart",
        "help_k4_long": "Halten=Aus",
        "help_hint": "K1 halten=Hilfe",
        "lan_qr": "QR scannen",
        "waiting_title": "Warten...",
        "waiting_line2": "Im Web erzeugen",
        "waiting_line3": "Auto-Update",
        "qr_expired_title": "QR abgelaufen",
        "qr_expired_line2": "Falls nicht verbunden",
        "qr_expired_line3": "Neu holen",
        "wifi_status": "WiFi-Status",
        "hotspot": "Hotspot",
        "waiting_phone": "Warte auf Handy",
        "connected": "Verbunden",
        "unknown": "Unbekannt",
        "check_network": "Netz prüfen...",
        "please_wait": "Bitte warten",
        "disconnecting": "Trenne WiFi...",
        "restart_hotspot": "Hotspot neu starten",
        "boot_subtitle": "AI-Gateway",
        "booting": "Starte...",
        "error_title": "Fehler",
    },
    "fr": {
        "help_buttons": "Boutons",
        "help_k1": "Scanner QR",
        "help_k2": "Discussions",
        "help_k3": "WiFi",
        "help_k4_short": "Court=Redém.",
        "help_k4_long": "Long=Éteindre",
        "help_hint": "Maintenir K1=aide",
        "lan_qr": "Scanner le QR",
        "waiting_title": "En attente...",
        "waiting_line2": "Créer sur le web",
        "waiting_line3": "Mise à jour auto",
        "qr_expired_title": "QR expiré",
        "qr_expired_line2": "Si non connecté",
        "qr_expired_line3": "En obtenir un neuf",
        "wifi_status": "État WiFi",
        "hotspot": "Point d'accès",
        "waiting_phone": "Attend téléphone",
        "connected": "Connecté",
        "unknown": "Inconnu",
        "check_network": "Vérifier réseau...",
        "please_wait": "Patientez svp",
        "disconnecting": "Coupure WiFi...",
        "restart_hotspot": "Relance du hotspot",
        "boot_subtitle": "Passerelle IA",
        "booting": "Démarrage...",
        "error_title": "Erreur",
    },
    "pt": {
        "help_buttons": "Botões",
        "help_k1": "Escanear QR",
        "help_k2": "Conversas",
        "help_k3": "WiFi",
        "help_k4_short": "Toque=Reiniciar",
        "help_k4_long": "Segurar=Desligar",
        "help_hint": "Segurar K1=ajuda",
        "lan_qr": "Escanear QR",
        "waiting_title": "Aguardando...",
        "waiting_line2": "Gerar na web",
        "waiting_line3": "Atualiza auto",
        "qr_expired_title": "QR expirado",
        "qr_expired_line2": "Se não conectado",
        "qr_expired_line3": "Obtenha um novo",
        "wifi_status": "Estado WiFi",
        "hotspot": "Ponto acesso",
        "waiting_phone": "Aguardando telefone",
        "connected": "Conectado",
        "unknown": "Desconhecido",
        "check_network": "Verificar rede...",
        "please_wait": "Aguarde por favor",
        "disconnecting": "Desconectando WiFi...",
        "restart_hotspot": "Reiniciar hotspot",
        "boot_subtitle": "Porta IA",
        "booting": "Iniciando...",
        "error_title": "Erro",
    },
    "it": {
        "help_buttons": "Pulsanti",
        "help_k1": "Scansiona QR",
        "help_k2": "Chat",
        "help_k3": "WiFi",
        "help_k4_short": "Tocca=Riavvia",
        "help_k4_long": "Tieni=Spegni",
        "help_hint": "Tieni K1=aiuto",
        "lan_qr": "Scansiona QR",
        "waiting_title": "In attesa...",
        "waiting_line2": "Genera sul web",
        "waiting_line3": "Aggiorna auto",
        "qr_expired_title": "QR scaduto",
        "qr_expired_line2": "Se non connesso",
        "qr_expired_line3": "Ottienine uno nuovo",
        "wifi_status": "Stato WiFi",
        "hotspot": "Hotspot",
        "waiting_phone": "Attesa telefono",
        "connected": "Connesso",
        "unknown": "Sconosciuto",
        "check_network": "Controlla rete...",
        "please_wait": "Attendere prego",
        "disconnecting": "Disconnessione WiFi...",
        "restart_hotspot": "Riavvia hotspot",
        "boot_subtitle": "Gateway AI",
        "booting": "Avvio...",
        "error_title": "Errore",
    },
    "ru": {
        "help_buttons": "Кнопки",
        "help_k1": "Сканировать QR",
        "help_k2": "Чаты",
        "help_k3": "WiFi",
        "help_k4_short": "Коротко=Рестарт",
        "help_k4_long": "Долго=Выкл.",
        "help_hint": "K1 долго=помощь",
        "lan_qr": "Скан QR",
        "waiting_title": "Ожидание...",
        "waiting_line2": "Создать на сайте",
        "waiting_line3": "Автообновл.",
        "qr_expired_title": "QR истёк",
        "qr_expired_line2": "Если не подключён",
        "qr_expired_line3": "Получить новый",
        "wifi_status": "Статус WiFi",
        "hotspot": "Точка доступа",
        "waiting_phone": "Ждём телефон",
        "connected": "Подключено",
        "unknown": "Неизвестно",
        "check_network": "Проверка сети...",
        "please_wait": "Подождите",
        "disconnecting": "Отключение WiFi...",
        "restart_hotspot": "Перезапуск точки",
        "boot_subtitle": "ИИ-шлюз",
        "booting": "Запуск...",
        "error_title": "Ошибка",
    },
    "nl": {
        "help_buttons": "Knoppen",
        "help_k1": "Scan QR",
        "help_k2": "Chats",
        "help_k3": "WiFi",
        "help_k4_short": "Tik=Herstart",
        "help_k4_long": "Vasth.=Uit",
        "help_hint": "K1 vasth.=hulp",
        "lan_qr": "Scan de QR",
        "waiting_title": "Wachten...",
        "waiting_line2": "Genereer op web",
        "waiting_line3": "Auto vernieuwt",
        "qr_expired_title": "QR verlopen",
        "qr_expired_line2": "Indien niet verbonden",
        "qr_expired_line3": "Haal een nieuwe",
        "wifi_status": "WiFi-status",
        "hotspot": "Hotspot",
        "waiting_phone": "Wachten op telefoon",
        "connected": "Verbonden",
        "unknown": "Onbekend",
        "check_network": "Netwerk checken...",
        "please_wait": "Even wachten",
        "disconnecting": "WiFi verbreken...",
        "restart_hotspot": "Hotspot herstarten",
        "boot_subtitle": "AI-gateway",
        "booting": "Opstarten...",
        "error_title": "Fout",
    },
    "pl": {
        "help_buttons": "Przyciski",
        "help_k1": "Skanuj QR",
        "help_k2": "Czaty",
        "help_k3": "WiFi",
        "help_k4_short": "Dotkn=Restart",
        "help_k4_long": "Przytrz.=Wyłącz",
        "help_hint": "Przytrz. K1=pomoc",
        "lan_qr": "Skanuj QR",
        "waiting_title": "Czekam...",
        "waiting_line2": "Generuj w sieci",
        "waiting_line3": "Auto odświeża",
        "qr_expired_title": "QR wygasł",
        "qr_expired_line2": "Jeśli nie połączono",
        "qr_expired_line3": "Pobierz nowy",
        "wifi_status": "Status WiFi",
        "hotspot": "Hotspot",
        "waiting_phone": "Czekam na telefon",
        "connected": "Połączono",
        "unknown": "Nieznany",
        "check_network": "Sprawdź sieć...",
        "please_wait": "Proszę czekać",
        "disconnecting": "Rozłączanie WiFi...",
        "restart_hotspot": "Restart hotspotu",
        "boot_subtitle": "Brama AI",
        "booting": "Uruchamianie...",
        "error_title": "Błąd",
    },
    "vi": {
        "help_buttons": "Nút",
        "help_k1": "Quét mã QR",
        "help_k2": "Trò chuyện",
        "help_k3": "WiFi",
        "help_k4_short": "Bấm=Khởi động lại",
        "help_k4_long": "Giữ=Tắt nguồn",
        "help_hint": "Giữ K1=trợ giúp",
        "lan_qr": "Quét để mở",
        "waiting_title": "Đang chờ...",
        "waiting_line2": "Tạo trên web",
        "waiting_line3": "Tự làm mới",
        "qr_expired_title": "Mã QR hết hạn",
        "qr_expired_line2": "Nếu chưa kết nối",
        "qr_expired_line3": "Lấy mã mới",
        "wifi_status": "Trạng thái WiFi",
        "hotspot": "Điểm phát sóng",
        "waiting_phone": "Chờ điện thoại",
        "connected": "Đã kết nối",
        "unknown": "Không rõ",
        "check_network": "Kiểm tra mạng...",
        "please_wait": "Vui lòng đợi",
        "disconnecting": "Đang ngắt WiFi...",
        "restart_hotspot": "Mở lại điểm phát",
        "boot_subtitle": "Cổng AI",
        "booting": "Đang khởi động...",
        "error_title": "Lỗi",
    },
    "hi": {
        "help_buttons": "बटन",
        "help_k1": "स्कैन करके खोलें",
        "help_k2": "चैट",
        "help_k3": "वाई-फ़ाई",
        "help_k4_short": "दबाएँ=रीस्टार्ट",
        "help_k4_long": "दबाकर रखें=बंद",
        "help_hint": "पहला बटन दबाए रखें=मदद",
        "lan_qr": "स्कैन करके खोलें",
        "waiting_title": "प्रतीक्षा...",
        "waiting_line2": "वेब पर बनाएँ",
        "waiting_line3": "ऑटो रीफ़्रेश",
        "qr_expired_title": "कोड समाप्त",
        "qr_expired_line2": "यदि कनेक्ट न हुआ",
        "qr_expired_line3": "नया लें",
        "wifi_status": "वाई-फ़ाई स्थिति",
        "hotspot": "हॉटस्पॉट",
        "waiting_phone": "फ़ोन की प्रतीक्षा",
        "connected": "कनेक्टेड",
        "unknown": "अज्ञात",
        "check_network": "नेटवर्क जाँच...",
        "please_wait": "कृपया प्रतीक्षा करें",
        "disconnecting": "वाई-फ़ाई कट रहा है...",
        "restart_hotspot": "हॉटस्पॉट फिर से शुरू",
        "boot_subtitle": "स्मार्ट गेटवे",
        "booting": "प्रारंभ...",
        "error_title": "त्रुटि",
    },
    "ar": {
        "help_buttons": "الأزرار",
        "help_k1": "امسح الرمز",
        "help_k2": "المحادثات",
        "help_k3": "واي فاي",
        "help_k4_short": "اضغط لإعادة التشغيل",
        "help_k4_long": "اضغط مطولًا للإيقاف",
        "help_hint": "اضغط الأول مطولًا للمساعدة",
        "lan_qr": "امسح للفتح",
        "waiting_title": "انتظار...",
        "waiting_line2": "أنشئه على الويب",
        "waiting_line3": "تحديث تلقائي",
        "qr_expired_title": "انتهت صلاحية الرمز",
        "qr_expired_line2": "إذا لم تتصل بعد",
        "qr_expired_line3": "احصل على رمز جديد",
        "wifi_status": "حالة واي فاي",
        "hotspot": "نقطة اتصال",
        "waiting_phone": "بانتظار الهاتف",
        "connected": "متصل",
        "unknown": "غير معروف",
        "check_network": "فحص الشبكة...",
        "please_wait": "الرجاء الانتظار",
        "disconnecting": "جارٍ قطع واي فاي...",
        "restart_hotspot": "إعادة تشغيل نقطة الاتصال",
        "boot_subtitle": "بوابة ذكية",
        "booting": "جارٍ التشغيل...",
        "error_title": "خطأ",
    },
    "tr": {
        "help_buttons": "Düğmeler",
        "help_k1": "QR Tara",
        "help_k2": "Sohbetler",
        "help_k3": "WiFi",
        "help_k4_short": "Bas=Tekrar başlat",
        "help_k4_long": "Basılı Tut=Kapat",
        "help_hint": "K1 basılı=yardım",
        "lan_qr": "Tara ve aç",
        "waiting_title": "Bekleniyor...",
        "waiting_line2": "Web'de oluştur",
        "waiting_line3": "Otomatik yenile",
        "qr_expired_title": "QR süresi doldu",
        "qr_expired_line2": "Bağlanmadıysa",
        "qr_expired_line3": "Yeni bir tane al",
        "wifi_status": "WiFi Durumu",
        "hotspot": "Erişim Noktası",
        "waiting_phone": "Telefon bekleniyor",
        "connected": "Bağlı",
        "unknown": "Bilinmiyor",
        "check_network": "Ağ kontrol...",
        "please_wait": "Lütfen bekleyin",
        "disconnecting": "WiFi bağlantı kesiliyor...",
        "restart_hotspot": "Erişim noktası başlıyor",
        "boot_subtitle": "AI Geçidi",
        "booting": "Başlatılıyor...",
        "error_title": "Hata",
    },
    "uk": {
        "help_buttons": "Кнопки",
        "help_k1": "Сканувати QR",
        "help_k2": "Чати",
        "help_k3": "WiFi",
        "help_k4_short": "Торк=Перезапуск",
        "help_k4_long": "Трим.=Вимк.",
        "help_hint": "K1 трим.=довідка",
        "lan_qr": "Скануйте QR",
        "waiting_title": "Очікування...",
        "waiting_line2": "Створіть у вебі",
        "waiting_line3": "Автооновлення",
        "qr_expired_title": "QR застарів",
        "qr_expired_line2": "Якщо не під'єднано",
        "qr_expired_line3": "Отримайте новий",
        "wifi_status": "Статус WiFi",
        "hotspot": "Точка доступу",
        "waiting_phone": "Чекаємо телефон",
        "connected": "Під'єднано",
        "unknown": "Невідомо",
        "check_network": "Перевірка мережі...",
        "please_wait": "Зачекайте",
        "disconnecting": "Від'єднання WiFi...",
        "restart_hotspot": "Перезапуск точки",
        "boot_subtitle": "AI-шлюз",
        "booting": "Запуск...",
        "error_title": "Помилка",
    },
    "id": {
        "help_buttons": "Tombol",
        "help_k1": "Pindai QR",
        "help_k2": "Obrolan",
        "help_k3": "WiFi",
        "help_k4_short": "Ketuk=Restart",
        "help_k4_long": "Tahan=Matikan",
        "help_hint": "Tahan K1=bantuan",
        "lan_qr": "Pindai untuk buka",
        "waiting_title": "Menunggu...",
        "waiting_line2": "Buat di web",
        "waiting_line3": "Perbarui otomatis",
        "qr_expired_title": "QR kedaluwarsa",
        "qr_expired_line2": "Jika belum terhubung",
        "qr_expired_line3": "Ambil yang baru",
        "wifi_status": "Status WiFi",
        "hotspot": "Titik Akses",
        "waiting_phone": "Menunggu ponsel",
        "connected": "Terhubung",
        "unknown": "Tidak dikenal",
        "check_network": "Periksa jaringan...",
        "please_wait": "Mohon tunggu",
        "disconnecting": "Memutus WiFi...",
        "restart_hotspot": "Mulai ulang hotspot",
        "boot_subtitle": "Gerbang AI",
        "booting": "Memulai...",
        "error_title": "Kesalahan",
    },
    "fa": {
        "help_buttons": "دکمه‌ها",
        "help_k1": "اسکن کد",
        "help_k2": "گفتگوها",
        "help_k3": "وای‌فای",
        "help_k4_short": "فشار: راه‌اندازی مجدد",
        "help_k4_long": "نگه‌دار: خاموش",
        "help_hint": "اولی را نگه دارید: راهنما",
        "lan_qr": "اسکن برای باز کردن",
        "waiting_title": "در انتظار...",
        "waiting_line2": "در وب بسازید",
        "waiting_line3": "به‌روزرسانی خودکار",
        "qr_expired_title": "کد منقضی شد",
        "qr_expired_line2": "اگر متصل نشدید",
        "qr_expired_line3": "یک مورد جدید بگیرید",
        "wifi_status": "وضعیت وای‌فای",
        "hotspot": "نقطه اتصال",
        "waiting_phone": "در انتظار گوشی",
        "connected": "متصل",
        "unknown": "ناشناخته",
        "check_network": "بررسی شبکه...",
        "please_wait": "لطفاً صبر کنید",
        "disconnecting": "قطع اتصال وای‌فای...",
        "restart_hotspot": "راه‌اندازی مجدد نقطه",
        "boot_subtitle": "درگاه هوشمند",
        "booting": "در حال راه‌اندازی...",
        "error_title": "خطا",
    },
    "th": {
        "help_buttons": "ปุ่ม",
        "help_k1": "สแกนคิวอาร์",
        "help_k2": "แชท",
        "help_k3": "ไวไฟ",
        "help_k4_short": "แตะเพื่อรีสตาร์ท",
        "help_k4_long": "กดค้างเพื่อปิดเครื่อง",
        "help_hint": "กดปุ่มแรกค้างเพื่อดูวิธีใช้",
        "lan_qr": "สแกนเพื่อเปิด",
        "waiting_title": "กำลังรอ",
        "waiting_line2": "สร้างบนเว็บ",
        "waiting_line3": "รีเฟรชอัตโนมัติ",
        "qr_expired_title": "คิวอาร์หมดอายุ",
        "qr_expired_line2": "หากยังไม่ได้เชื่อมต่อ",
        "qr_expired_line3": "รับใหม่",
        "wifi_status": "สถานะไวไฟ",
        "hotspot": "ฮอตสปอต",
        "waiting_phone": "รอโทรศัพท์",
        "connected": "เชื่อมต่อแล้ว",
        "unknown": "ไม่ทราบ",
        "check_network": "ตรวจสอบเครือข่าย",
        "please_wait": "โปรดรอ",
        "disconnecting": "กำลังตัดไวไฟ",
        "restart_hotspot": "รีสตาร์ทฮอตสปอต",
        "boot_subtitle": "เกตเวย์อัจฉริยะ",
        "booting": "กำลังเริ่ม",
        "error_title": "ข้อผิดพลาด",
    },
}
